### PR TITLE
Blender 2.8 Update for "import_pix.py"

### PR DESCRIPTION
**Pull request by Medstar117**
I believe that I have successfully managed to get this plugin to work on Blender 2.8. Due to the fact that I have never used DirectX PIX, I can't 100% confirm that this will work perfectly as I don't know the exact CSV output--I can only assume based on how you've set your script to read the CSV rows/columns and from the vivid screenshots you have on your "Reversing a DirectX Game" blog.

However, I have created and tested a slightly modified version of this script in a personal repository for use with RenderDoc; and I can indeed confirm that my modified script works perfectly with Blender 2.8 (currently tested with 2.83.3 LTS). Here's the link to it if anyone's interested: https://github.com/Medstar117/BlenderDoc-PIX-CSV

All rights reserved, of course, concerning the modified script in the link above. I left certain modifications that I added to my version of the script out of this PR since, again, I don't know the CSV output that DirectX PIX produces; and I don't know if what I changed for RenderDoc would drastically change the output for DirectX PIX data (I had to tweak a few modifiers for use with RenderDoc since things were VERY flipped for both vertices and UV's; more info in the link above and in the script itself).

Thank you for making such an awesome script; and I hope this proves beneficial both for you and for everyone else who uses it :)

--------------------------------------------------------------

Additions:
- Updated all "tessfaces" API calls to use equivalent Blender 2.8 data types since tessfaces was completely removed.

- Added a lot of comments to describe what section does what for those who are interested.

Removals:
- Commented out unnecessary code that looked to be used when calculating how many faces would be in a given CSV file. The calculation was already commented out; however, the extra step to seek back to the top of the file and skip the header again was not.

- Removed unnecessary/unused variables (such as bpy.props.FloatProperty).

Modifications:
- Cleaned up the code and reorganized certain variables and imports to be more pleasing to the eye when navigating the code (in my opinion).

- Left some commented debugging(?) code in case someone wishes to use them in the future.

### CODE REVIEW

**Comment by sbobovyc** [comment]
Thanks for updating this script. I have moved to using raw2obj.py  (found in GameTools/common) which supports converting of csv, html and binary files to OBJ.

**Comment by Medstar117** [comment]
Sweet, thanks for the info; and no problem :)

I personally like this plugin since it nixes certain steps that I would have to take with what I'm doing with the models I grab; it just saves time for me imo :D

Does raw2obj.py work the same way as this aside from Blender being out of the picture? I've seen that tool mentioned a lot, but I have yet to use it.

Again, thank you for your work.

**Comment by sbobovyc** [comment]
Thank you for the kind words! I wrote raw2obj.py because I kept on writing code that would dump 3d objects to obj format because it is human readable, so I decided to generalize it.

**Comment by Matscrich** [comment]
Hello Sbobovyc and Medstar117, thank you for the Blender plug-in. It allows me to import models from my favorite game into Blender.
I have one question though: Is there a possibility for "batch importing" the models ?
In my game, the models are separated by texture draws, for instance one character can be in 15 parts.
I am interested in the map geometry of the game which comes by chunks of about 80 models each. For now i am importing them manually 1 by 1.
If it is impossible to import several CSVs, could i convert them with your other tool "raw2obj" and then import them all into Blender at once ?
Thank you.

**Comment by sbobovyc** [comment]
You can look into calling the OBJ import from a python script.

**Comment by Matscrich** [comment]
> 
> 
> You can look into calling the OBJ import from a python script.

Okay, so that could work with OBJs but not CSVs ?
And is it possible to get the imported files to automatically have a more significant name than "name", "name.001", "name.002"...etc ? Like the name of the csv file or the number of the drawcall.
Thanks

**Pull request merged**
